package com.comandante.creeper.npc;

import com.comandante.creeper.stat.StatsBuilder;

public class NpcStats {
    public final static StatsBuilder DERPER = new StatsBuilder()
            .setStrength(5)
            .setWillpower(1)
            .setAim(1)
            .setAgile(1)
            .setArmorRating(5)
            .setMeleSkill(5)
            .setCurrentHealth(100)
            .setMaxHealth(100)
            .setWeaponRatingMin(5)
            .setWeaponRatingMax(10)
            .setNumberweaponOfRolls(1)
            .setExperience(3);

    public final static StatsBuilder DRUGGED_PIMP = new StatsBuilder()
            .setStrength(5)
            .setWillpower(1)
            .setAim(1)
            .setAgile(1)
            .setArmorRating(5)
            .setMeleSkill(5)
            .setCurrentHealth(150)
            .setMaxHealth(150)
            .setWeaponRatingMin(5)
            .setWeaponRatingMax(10)
            .setNumberweaponOfRolls(1)
            .setExperience(3)
            .setGoldDrop(5);

    public final static StatsBuilder TREE_BERSERKER = new StatsBuilder()
            .setStrength(8)
            .setWillpower(1)
            .setAim(1)
            .setAgile(1)
            .setArmorRating(8)
            .setMeleSkill(6)
            .setCurrentHealth(200)
            .setMaxHealth(200)
            .setWeaponRatingMin(8)
            .setWeaponRatingMax(13)
            .setNumberweaponOfRolls(1)
            .setExperience(150)
            .setGoldDrop(12);


    public final static StatsBuilder SWAMP_BERSERKER = new StatsBuilder()
            .setStrength(11)
            .setWillpower(2)
            .setAim(2)
            .setAgile(1)
            .setArmorRating(8)
            .setMeleSkill(6)
            .setCurrentHealth(230)
            .setMaxHealth(230)
            .setWeaponRatingMin(10)
            .setWeaponRatingMax(13)
            .setNumberweaponOfRolls(1)
            .setExperience(190)
            .setGoldDrop(20);

    public final static StatsBuilder BERG_ORC = new StatsBuilder()
            .setStrength(11)
            .setWillpower(2)
            .setAim(2)
            .setAgile(1)
            .setArmorRating(8)
            .setMeleSkill(6)
            .setCurrentHealth(230)
            .setMaxHealth(230)
            .setWeaponRatingMin(10)
            .setWeaponRatingMax(13)
            .setNumberweaponOfRolls(1)
            .setExperience(190)
            .setGoldDrop(20);

    public final static StatsBuilder SWAMP_BEAR = new StatsBuilder()
            .setStrength(15)
            .setWillpower(3)
            .setAim(3)
            .setAgile(3)
            .setArmorRating(8)
            .setMeleSkill(6)
            .setCurrentHealth(300)
            .setMaxHealth(300)
            .setWeaponRatingMin(10)
            .setWeaponRatingMax(16)
            .setNumberweaponOfRolls(1)
            .setExperience(300)
            .setGoldDrop(40);

    public final static StatsBuilder REDEYED_BEAR = new StatsBuilder()
            .setStrength(15)
            .setWillpower(3)
            .setAim(3)
            .setAgile(3)
            .setArmorRating(8)
            .setMeleSkill(6)
            .setCurrentHealth(300)
            .setMaxHealth(300)
            .setWeaponRatingMin(10)
            .setWeaponRatingMax(16)
            .setNumberweaponOfRolls(1)
            .setExperience(300)
            .setGoldDrop(40);

    public final static StatsBuilder GRAY_EKIMMU = new StatsBuilder()
            .setStrength(20)
            .setWillpower(4)
            .setAim(4)
            .setAgile(5)
            .setArmorRating(11)
            .setMeleSkill(8)
            .setCurrentHealth(450)
            .setMaxHealth(450)
            .setWeaponRatingMin(12)
            .setWeaponRatingMax(18)
            .setNumberweaponOfRolls(1)
            .setExperience(450);

    public final static StatsBuilder STEALTH_PANTHER = new StatsBuilder()
            .setStrength(23)
            .setWillpower(4)
            .setAim(5)
            .setAgile(6)
            .setArmorRating(11)
            .setMeleSkill(8)
            .setCurrentHealth(500)
            .setMaxHealth(500)
            .setWeaponRatingMin(10)
            .setWeaponRatingMax(20)
            .setNumberweaponOfRolls(1)
            .setExperience(510);

    public final static StatsBuilder DEATH_GRIFFIN = new StatsBuilder()
            .setStrength(55)
            .setWillpower(30)
            .setAim(24)
            .setAgile(24)
            .setArmorRating(20)
            .setMeleSkill(19)
            .setCurrentHealth(1000)
            .setMaxHealth(1000)
            .setWeaponRatingMin(20)
            .setWeaponRatingMax(65)
            .setNumberweaponOfRolls(1)
            .setExperience(2100);

    public final static StatsBuilder DEMON_SUCCUBUS = new StatsBuilder()
            .setStrength(70)
            .setWillpower(35)
            .setAim(14)
            .setAgile(14)
            .setArmorRating(25)
            .setMeleSkill(19)
            .setCurrentHealth(1200)
            .setMaxHealth(1200)
            .setWeaponRatingMin(35)
            .setWeaponRatingMax(60)
            .setNumberweaponOfRolls(1)
            .setExperience(2600);

    public final static StatsBuilder TIGER_MONOCERUS = new StatsBuilder()
            .setStrength(28)
            .setWillpower(10)
            .setAim(5)
            .setAgile(9)
            .setArmorRating(12)
            .setMeleSkill(19)
            .setCurrentHealth(600)
            .setMaxHealth(600)
            .setWeaponRatingMin(20)
            .setWeaponRatingMax(36)
            .setNumberweaponOfRolls(1)
            .setExperience(800);

    public final static StatsBuilder NIGHTMARE_TROLL = new StatsBuilder()
            .setStrength(34)
            .setWillpower(7)
            .setAim(6)
            .setAgile(6)
            .setArmorRating(18)
            .setMeleSkill(8)
            .setCurrentHealth(550)
            .setMaxHealth(550)
            .setWeaponRatingMin(5)
            .setWeaponRatingMax(32)
            .setNumberweaponOfRolls(1)
            .setExperience(720);

    public final static StatsBuilder RAZORCLAW_WOLF = new StatsBuilder()
            .setStrength(25)
            .setWillpower(10)
            .setAim(5)
            .setAgile(9)
            .setArmorRating(8)
            .setMeleSkill(12)
            .setCurrentHealth(500)
            .setMaxHealth(500)
            .setWeaponRatingMin(10)
            .setWeaponRatingMax(27)
            .setNumberweaponOfRolls(1)
            .setExperience(600);

    public final static StatsBuilder PHANTOM_WIZARD = new StatsBuilder()
            .setStrength(16)
            .setWillpower(9)
            .setAim(4)
            .setAgile(5)
            .setArmorRating(9)
            .setMeleSkill(8)
            .setCurrentHealth(400)
            .setMaxHealth(400)
            .setWeaponRatingMin(12)
            .setWeaponRatingMax(25)
            .setNumberweaponOfRolls(1)
            .setExperience(510);

    public final static StatsBuilder PHANTOM_KNIGHT = new StatsBuilder()
            .setStrength(28)
            .setWillpower(5)
            .setAim(5)
            .setAgile(6)
            .setArmorRating(14)
            .setMeleSkill(8)
            .setCurrentHealth(500)
            .setMaxHealth(500)
            .setWeaponRatingMin(10)
            .setWeaponRatingMax(20)
            .setNumberweaponOfRolls(1)
            .setExperience(600);

    public final static StatsBuilder PHANTOM_ORC = new StatsBuilder()
            .setStrength(23)
            .setWillpower(4)
            .setAim(5)
            .setAgile(6)
            .setArmorRating(11)
            .setMeleSkill(8)
            .setCurrentHealth(500)
            .setMaxHealth(500)
            .setWeaponRatingMin(10)
            .setWeaponRatingMax(20)
            .setNumberweaponOfRolls(1)
            .setExperience(510);

}
